from dotenv import load_dotenv
load_dotenv()

from langchain_mistralai import ChatMistralAI

model = ChatMistralAI(
    model="mistral-large-latest",
    temperature=0
)

while True:
    prompt = input("You: ")
    if(prompt.lower() == "exit"):
        break;
    response = model.invoke(prompt)

    print("-----------------------------This content is generated by the AI model Mistral : ------------------------------------------")
    print("AI: " + response.content)